automatic-update-detection=true
controller-dir=FCL-Wuzhongrentwo
update-detection-url=https://qwmike1145.github.io/version_map.json
min-memory-requirement=4
enable-announcement-component=true
announcement-url=https://qwmike1145.github.io/announcement.txt
download-online-authlib-injector=false
primary-nameserver=119.29.29.29
secondary-nameserver=8.8.8.8
qq-group-key=kx1j2WKH3rYX1zl5nknzHwNyGSXKGdf4
discord-url=https://qwmike1145.github.io
activity-main-title=\u96fe\u4e2d\u4eba\u6574\u5408\u5305 v1.16.0